/**
 * ~/.swarmflow/.env 的最小 .env 文件加载器。
 *
 * 将 KEY=VALUE 对加载到 process.env，具有覆盖语义——
 * .env 中的值优先于现有环境变量。
 * 这确保了在 `swarmflow init` 期间粘贴的密钥始终获胜。
 */

import { existsSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";
import { getSwarmflowHomeDir } from "./lib/home-path.js";

const ENV_FILE = ".env";

function envFilePath(homeDir?: string): string {
  return join(homeDir ?? getSwarmflowHomeDir(), ENV_FILE);
}

/**
 * 将 ~/.swarmflow/.env 加载到 process.env（覆盖模式）。
 * 如果文件不存在或无法读取，则静默跳过。
 */
export function loadDotenv(homeDir?: string): void {
  const path = envFilePath(homeDir);
  if (!existsSync(path)) return;

  let content: string;
  try {
    content = readFileSync(path, "utf-8");
  } catch {
    return;
  }

  for (const line of content.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eqIdx = trimmed.indexOf("=");
    if (eqIdx <= 0) continue;
    const key = trimmed.slice(0, eqIdx).trim();
    let value = trimmed.slice(eqIdx + 1).trim();
    // Strip surrounding quotes
    if ((value.startsWith('"') && value.endsWith('"'))
      || (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1);
    }
    process.env[key] = value;
  }
}

/**
 * 在 ~/.swarmflow/.env 中写入或更新密钥。
 * 保留现有条目；如果密钥已存在则更新值。
 */
export function setDotenvKey(key: string, value: string, homeDir?: string): void {
  const dir = homeDir ?? getSwarmflowHomeDir();
  mkdirSync(dir, { recursive: true });
  const path = envFilePath(dir);

  let lines: string[] = [];
  if (existsSync(path)) {
    try {
      lines = readFileSync(path, "utf-8").split("\n");
    } catch {
      lines = [];
    }
  }

  // Check if key already exists — update in place
  let found = false;
  for (let i = 0; i < lines.length; i++) {
    const trimmed = lines[i].trim();
    if (trimmed.startsWith(`${key}=`)) {
      lines[i] = `${key}=${value}`;
      found = true;
      break;
    }
  }

  if (!found) {
    // Add header comment if file is empty
    if (lines.length === 0 || (lines.length === 1 && lines[0].trim() === "")) {
      lines = [
        "# swarmflow API keys",
        `# Generated by 'swarmflow init'`,
        "",
      ];
    }
    lines.push(`${key}=${value}`);
  }

  // Ensure trailing newline
  const content = lines.join("\n").trimEnd() + "\n";
  writeFileSync(path, content, { mode: 0o600 });

  // Also set in current process so subsequent wizard steps can detect it
  process.env[key] = value;
}

/**
 * 从 ~/.swarmflow/.env 和当前进程环境中移除密钥。
 *
 * 注意：这仅移除 swarmflow 控制的内容。如果相同变量也在
 * 用户的 shell 中导出，它将在下次启动时重新出现（loadDotenv
 * 不会重新添加它，但 shell 值已在环境中）。向用户
 * 展示移除的调用者应该对 shell 源密钥进行说明。
 */
export function unsetDotenvKey(key: string, homeDir?: string): void {
  const path = envFilePath(homeDir ?? getSwarmflowHomeDir());

  if (existsSync(path)) {
    let lines: string[];
    try {
      lines = readFileSync(path, "utf-8").split("\n");
    } catch {
      lines = [];
    }
    const kept = lines.filter((line) => {
      const trimmed = line.trim();
      return !(trimmed.startsWith(`${key}=`));
    });
    if (kept.length !== lines.length) {
      const content = kept.join("\n").trimEnd() + "\n";
      writeFileSync(path, content, { mode: 0o600 });
    }
  }

  // Remove from the live process so the running session reflects the change.
  delete process.env[key];
}
